version: "3.7"

services:
  
  redis:
    image: redis:5
    ports:
      - "3306:3306"
    volumes:
      - ../src/data/redis:/data
    labels:
      maintainer: "Salle MPWAR Maintainers"
    command: redis-server --appendonly yes

  http:
    image: nginx:stable
    volumes:
      - ./src:/usr/share/nginx/html
    labels:
      maintainer: "Salle MPWAR Maintainers"
    ports:
      - "8085:80"
    links:
      - php:php

  php:
    image: php:7.3-fpm
    links:
      - redis
    volumes:
      - ./src:/usr/share/nginx/html
    labels:
      maintainer: "Salle MPWAR Maintainers"